spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.ylxteach.net:3366/paperBase?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: Administrator
    password: XWClassroom20202023
    #url: jdbc:mysql://localhost:3306/paper_base?useUnicode=true&characterEncoding=utf8&useSSL=false
    #username: root
    #password: hjh123456
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    encoding:
      charset: utf-8

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/extend/*.xml

logging:
  level:
    com.example.mybatisplus.mapper: debug
file-upload-path: ./file
